# Site settings
title: Orlando Devs
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Official account for the Orlando Devs Community!
  We are an inclusive community, open to everyone who has a passion in software
  development in the Orlando area.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://orlandodevs.github.io" # the base hostname & protocol for your site
twitter_username: OrlandoDevs
github_username:  OrlandoDevs

# Build settings
markdown: kramdown

# Outputting
permalink:     /blog/:title/
paginate_path: /page:num
timezone:      null
